 
package presentacion;

import Datos.personaDAO;
import Datos.telefonoDAO;
import Interfaces.ClsPersona;
import Interfaces.Telefono;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionPersonas extends javax.swing.JFrame {
    public int idSel;
    public boolean opc;
    DefaultTableModel modelo;
    String cabecera[] = {"IdTelefono", "Numero", "Principal", "Estado", "idPersona" } ;
            
    public GestionPersonas() throws Exception {
        this.opc = true;
        this.idSel = -1;
        initComponents();       
        this.setLocationRelativeTo(null); // centrar el formulario
        modelo = new DefaultTableModel(null, cabecera );
        this.tbTelefonos.setModel(modelo);
        activar(false);
        cargarTelefonos();
        cargarPersonas();

    }

    
    private void cargarPersonas() throws Exception{
        personaDAO objDAO = new personaDAO();
        ArrayList <ClsPersona> lista;
        try{
            lista = objDAO.listadoPersonas();
            for ( ClsPersona obj : lista ) {
                this.cbPersonas.addItem( obj );
            }
        } 
        catch (Exception ex) {
                throw ex;
        }
    }
    
    
    private void activar(boolean valor){
        this.txtNumero.setEnabled(valor);
        this.chkPrincipal.setEnabled(valor);
        this.txtEstado.setEnabled(valor);
        this.cbPersonas.setEnabled(valor);
        this.cmdGrabar.setEnabled(valor);
    }
    
    
    private void cargarTelefonos() throws Exception{
        telefonoDAO objDAO = new telefonoDAO();
        ArrayList<Telefono> lista;
        try{
            lista = objDAO.listadoTelefonos();
            for ( Telefono obj : lista ){
                String fila[] = { String.valueOf( obj.getIdTelefono()), 
                                  obj.getNumero(), 
                                  String.valueOf(obj.getPrincipal()), 
                                  String.valueOf(obj.getEstado()),  
                                  String.valueOf(obj.getIdPersona())};
                modelo.addRow(fila);
            }
        } 
        catch (Exception ex) {
            throw ex;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cmdCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTelefonos = new javax.swing.JTable();
        cmdGrabar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbPersonas = new javax.swing.JComboBox();
        chkPrincipal = new javax.swing.JCheckBox();
        txtEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cmdBuscar = new javax.swing.JButton();
        rb_EsAct = new javax.swing.JRadioButton();
        rb_EsIna = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmdCerrar.setText("Cerrar");
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero :");

        jLabel3.setText("Estado :");

        tbTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTelefonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTelefonosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTelefonos);

        cmdGrabar.setText("Grabar");
        cmdGrabar.setEnabled(false);
        cmdGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGrabarActionPerformed(evt);
            }
        });

        cmdActualizar.setText("Actualizar");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });

        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        jLabel5.setText("Persona :");

        chkPrincipal.setText("Principal");

        jLabel2.setText("Numero :");

        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_EsAct);
        rb_EsAct.setText("Activo");

        buttonGroup1.add(rb_EsIna);
        rb_EsIna.setText("inactivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(447, 447, 447))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chkPrincipal))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(rb_EsAct)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb_EsIna)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(105, 105, 105)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmdGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(cmdCerrar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdGrabar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdActualizar)
                    .addComponent(chkPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_EsAct)
                        .addComponent(rb_EsIna))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdNuevo)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cmdCerrar)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(537, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        try{
            if ( this.idSel == -1){
                JOptionPane.showMessageDialog(rootPane, "Selecciona un telefono");
                return;
            }
            this.cmdGrabar.setEnabled(true);
            this.cmdNuevo.setEnabled(false);
            activar(true);      
            this.opc = false;
        } catch (Exception ex) {
            throw ex;
        }
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
       activar(true);
       this.cmdNuevo.setEnabled(false);
       this.opc = true;
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGrabarActionPerformed
        if ( this.txtNumero.getText().length() == 0  ){
             JOptionPane.showMessageDialog(rootPane, "Ingresar Numero");
             return;
        }
        //...
       
       Telefono tel;
       telefonoDAO objDAO = new telefonoDAO();
       char  princ;
       if (this.chkPrincipal.isSelected())
            princ = 0;
        else
            princ = 1;
       ClsPersona per = (ClsPersona) this.cbPersonas.getSelectedItem();
       int rbestado=0;
       if(rb_EsAct.isSelected()){
           rbestado=0;
       }else if(rb_EsIna.isSelected()){
           rbestado=1;
       }
       try{
           if (this.opc == true){        // cuando es nuevo
                tel = new Telefono( this.txtNumero.getText(),
                                       princ, 
                                       rbestado,                                   
                                       per.getIdPersona());
                objDAO.agregarTelefono(tel);
                JOptionPane.showMessageDialog(rootPane, "Telefono registrado");
            }
            else{        // cuando es actualizar
                tel = new Telefono( this.idSel,
                                       this.txtNumero.getText(),
                                       princ, 
                                       rbestado,                                   
                                       per.getIdPersona());
                objDAO.modificarTelefono(tel);
                JOptionPane.showMessageDialog(rootPane, "Telefono actualizado");
           }
            activar(false);
            modelo.setRowCount(0);
            cargarTelefonos();
        } 
       catch (Exception ex) {
            /*try {
                throw ex;
            } catch (Exception ex1) {
                Logger.getLogger(GestionPersonas.class.getName()).log(Level.SEVERE, null, ex1);
            }*/
       }
        
    }//GEN-LAST:event_cmdGrabarActionPerformed

    void buscarTelefono( String numero ) throws Exception{
        telefonoDAO objDAO = new telefonoDAO();
        ArrayList<Telefono> lista;
        try {
            lista = objDAO.buscarTelefono( numero );
            for ( Telefono obj : lista ){
                String fila[]= { String.valueOf( obj.getIdTelefono()), 
                                  obj.getNumero(), 
                                  String.valueOf(obj.getPrincipal()), 
                                  String.valueOf(obj.getEstado()),  
                                  String.valueOf(obj.getIdPersona())};
                modelo.addRow(fila);
            }
        } 
        catch (Exception ex) {
            throw ex;
        }
    }
        
    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        try{
            if ( this.txtBuscar.getText().length() == 0){
                JOptionPane.showMessageDialog(rootPane, "Ingresar Numero");
                return;
            }
            modelo.setRowCount(0);
            this.buscarTelefono( this.txtBuscar.getText());
        } 
        catch (Exception ex) {
            try {
                throw ex;
            } catch (Exception ex1) {
                Logger.getLogger(GestionPersonas.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void tbTelefonosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTelefonosMouseClicked
        int fila = this.tbTelefonos.getSelectedRow();
        this.txtNumero.setText( modelo.getValueAt(fila, 1 ).toString() );
        if ("T".equals(modelo.getValueAt(fila, 2).toString()) )
            this.chkPrincipal.setSelected(true);
        else
            this.chkPrincipal.setSelected(false);
        this.txtEstado.setText( modelo.getValueAt(fila, 3).toString() );
        this.cbPersonas.setSelectedIndex( Integer.parseInt(modelo.getValueAt(fila, 4).toString()) - 1);
        this.idSel = Integer.parseInt(modelo.getValueAt(fila, 0).toString());
   
    }//GEN-LAST:event_tbTelefonosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionPersonas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(GestionPersonas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbPersonas;
    private javax.swing.JCheckBox chkPrincipal;
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdGrabar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_EsAct;
    private javax.swing.JRadioButton rb_EsIna;
    private javax.swing.JTable tbTelefonos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
