/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author yampier
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Operaciones OP;
    Consultas CS;
    Procesos PRO;
    Reportes RP;
    Configuracion CONF;
    
    public Principal() throws Exception {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.PRO= new Procesos();
         this.RP= new Reportes();
        this.OP= new Operaciones();
        this.CONF= new Configuracion();
        this.CS= new Consultas();
         
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_reportes = new javax.swing.JButton();
        btn_configuraciones = new javax.swing.JButton();
        btn_procesos = new javax.swing.JButton();
        btn_consultas = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        btn_operaciones = new javax.swing.JButton();
        Desk_Panel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 192, 45));

        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/repor.png"))); // NOI18N
        btn_reportes.setBorderPainted(false);
        btn_reportes.setContentAreaFilled(false);
        btn_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportesMouseClicked(evt);
            }
        });
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_configuraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/confguracion.png"))); // NOI18N
        btn_configuraciones.setBorderPainted(false);
        btn_configuraciones.setContentAreaFilled(false);
        btn_configuraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_configuraciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_configuracionesMouseClicked(evt);
            }
        });
        btn_configuraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionesActionPerformed(evt);
            }
        });

        btn_procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/procesos.png"))); // NOI18N
        btn_procesos.setBorderPainted(false);
        btn_procesos.setContentAreaFilled(false);
        btn_procesos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_procesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_procesosMouseClicked(evt);
            }
        });
        btn_procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesosActionPerformed(evt);
            }
        });

        btn_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/consultas.png"))); // NOI18N
        btn_consultas.setBorderPainted(false);
        btn_consultas.setContentAreaFilled(false);
        btn_consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultasMouseClicked(evt);
            }
        });
        btn_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultasActionPerformed(evt);
            }
        });

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/cerrar.png"))); // NOI18N
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_operaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/operaciones.png"))); // NOI18N
        btn_operaciones.setAlignmentX(0.5F);
        btn_operaciones.setBorderPainted(false);
        btn_operaciones.setContentAreaFilled(false);
        btn_operaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_operaciones.setDoubleBuffered(true);
        btn_operaciones.setPreferredSize(new java.awt.Dimension(622, 524));
        btn_operaciones.setVerifyInputWhenFocusTarget(false);
        btn_operaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_operacionesMouseClicked(evt);
            }
        });
        btn_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operacionesActionPerformed(evt);
            }
        });

        Desk_Panel.setBackground(new java.awt.Color(255, 204, 204));
        Desk_Panel.setPreferredSize(new java.awt.Dimension(776, 563));

        javax.swing.GroupLayout Desk_PanelLayout = new javax.swing.GroupLayout(Desk_Panel);
        Desk_Panel.setLayout(Desk_PanelLayout);
        Desk_PanelLayout.setHorizontalGroup(
            Desk_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        Desk_PanelLayout.setVerticalGroup(
            Desk_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jLabel1.setText("Operaciones");

        jLabel2.setText("Consultas");

        jLabel3.setText("Procesos");

        jLabel4.setText("Reportes");

        jLabel5.setText("Configuracion");

        jLabel6.setText("Cerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Desk_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_procesos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_configuraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_procesos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_configuraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desk_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesosActionPerformed
        // TODO add your handling code here:
        
        this.Desk_Panel.add(this.PRO);
        this.PRO.setBounds(0,0,this.Desk_Panel.getWidth(),this.Desk_Panel.getHeight());
        this.PRO.setVisible(true);
        this.btn_procesos.setEnabled(false);
        
            //intenal Frames cerrados
            this.OP.dispose();
            this.CS.dispose();
            this.RP.dispose();
            this.CONF.dispose();
            //botones habilitados
            this.btn_operaciones.setEnabled(true);
            this.btn_consultas.setEnabled(true);
            this.btn_reportes.setEnabled(true);
            this.btn_configuraciones.setEnabled(true);
        
    }//GEN-LAST:event_btn_procesosActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
       
        this.Desk_Panel.add(this.RP);
        this.RP.setBounds(0,0,this.Desk_Panel.getWidth(),this.Desk_Panel.getHeight());
        this.RP.setVisible(true);
        this.btn_reportes.setEnabled(false);
        
            //intenal Frames cerrados
            this.OP.dispose();
            this.CS.dispose();
            this.PRO.dispose();
            this.CONF.dispose();
        
            //botones habilitados
            this.btn_operaciones.setEnabled(true);
            this.btn_consultas.setEnabled(true);
            this.btn_procesos.setEnabled(true);
            this.btn_configuraciones.setEnabled(true);
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operacionesActionPerformed
        // TODO add your handling code here:
        
        this.Desk_Panel.add(this.OP);
        this.OP.setBounds(0,0,this.Desk_Panel.getWidth(),this.Desk_Panel.getHeight());
        this.OP.setVisible(true);
        this.btn_operaciones.setEnabled(false);
       
            //intenal Frames cerrados
            this.CS.dispose();
            this.PRO.dispose();
            this.RP.dispose();
            this.CONF.dispose();
            //botones habilitados
            
        
       this.btn_consultas.setEnabled(true);
            this.btn_procesos.setEnabled(true);
            this.btn_reportes.setEnabled(true);
            this.btn_configuraciones.setEnabled(true);

    }//GEN-LAST:event_btn_operacionesActionPerformed
    
    private void btn_configuracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionesActionPerformed
        // TODO add your handling code here:
        
        this.Desk_Panel.add(this.CONF);
        this.CONF.setBounds(0,0,this.Desk_Panel.getWidth(),this.Desk_Panel.getHeight());
        this.CONF.setVisible(true);
        this.btn_configuraciones.setEnabled(false);
        
           
        
    }//GEN-LAST:event_btn_configuracionesActionPerformed

    private void btn_operacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_operacionesMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btn_operacionesMouseClicked

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultasActionPerformed
        // TODO add your handling code here:
         
        this.Desk_Panel.add(this.CS);
        this.CS.setBounds(0,0,this.Desk_Panel.getWidth(),this.Desk_Panel.getHeight());
        this.CS.setVisible(true);
        this.btn_consultas.setEnabled(false);
         
            //intenal Frames cerrados
            
    }//GEN-LAST:event_btn_consultasActionPerformed

    private void btn_consultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultasMouseClicked
        // TODO add your handling code here:
        this.OP.dispose();
            this.PRO.dispose();
            this.RP.dispose();
            this.CONF.dispose();
            //botones habilitados
            
        
         this.btn_operaciones.setEnabled(true);
            this.btn_procesos.setEnabled(true);
            this.btn_reportes.setEnabled(true);
            this.btn_configuraciones.setEnabled(true);
        
    }//GEN-LAST:event_btn_consultasMouseClicked

    private void btn_procesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_procesosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_procesosMouseClicked

    private void btn_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_reportesMouseClicked

    private void btn_configuracionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_configuracionesMouseClicked
        // TODO add your handling code here:
          //intenal Frames cerrados
            this.OP.dispose();
            this.CS.dispose();
            this.PRO.dispose();
            this.RP.dispose();
        
            //botones habilitados
            this.btn_operaciones.setEnabled(true);
            this.btn_consultas.setEnabled(true);
            this.btn_procesos.setEnabled(true);
            this.btn_reportes.setEnabled(true);
    }//GEN-LAST:event_btn_configuracionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desk_Panel;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_configuraciones;
    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton btn_operaciones;
    private javax.swing.JButton btn_procesos;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
