/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JFrame;

/**
 *
 * @author yampier
 */
public class Reportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reportes
     */
    RP_Clientes RPclientes;
    RP_Compras RPcompras;
    RP_Movimientos RPmovimientos;
    RP_Productos RPproductos;
    RP_Proveedor RPproveedor;
    RP_Trabajador RPtrabajador;
    RP_Utilidad RPutilidad;
    RP_Ventas RPventas;

    public Reportes() {
        initComponents();
        this.setLocation(200, 50);
        RPclientes = new RP_Clientes();
        RPcompras = new RP_Compras();
        RPmovimientos = new RP_Movimientos();
        RPproductos = new RP_Productos();
        RPproveedor = new RP_Proveedor();
        RPtrabajador = new RP_Trabajador();
        RPutilidad = new RP_Utilidad();
        RPventas = new RP_Ventas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_RpVentas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_RpCompras = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_RpTrabajador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_RpClientes = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_RpCProveedor = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_RpProductos = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_RpUtilidad = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_RpMoviminetos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("REPORTES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione opciones:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBackground(null);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_RpVentas.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpVentas.setPreferredSize(new java.awt.Dimension(94, 94));
        btn_RpVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_RpVentas, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(null);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Compras"));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btn_RpCompras.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpCompras.setPreferredSize(new java.awt.Dimension(94, 94));
        btn_RpCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpComprasActionPerformed(evt);
            }
        });
        jPanel3.add(btn_RpCompras, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(null);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajador"));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btn_RpTrabajador.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpTrabajadorActionPerformed(evt);
            }
        });
        jPanel4.add(btn_RpTrabajador, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(null);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel5.setLayout(new java.awt.BorderLayout());

        btn_RpClientes.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpClientesActionPerformed(evt);
            }
        });
        jPanel5.add(btn_RpClientes, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(null);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel6.setLayout(new java.awt.BorderLayout());

        btn_RpCProveedor.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpCProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpCProveedorActionPerformed(evt);
            }
        });
        jPanel6.add(btn_RpCProveedor, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setBackground(null);
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPanel7.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btn_RpProductos.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpProductosActionPerformed(evt);
            }
        });
        jPanel7.add(btn_RpProductos, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel8.setBackground(null);
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilidad"));
        jPanel8.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel8.setLayout(new java.awt.BorderLayout());

        btn_RpUtilidad.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpUtilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpUtilidadActionPerformed(evt);
            }
        });
        jPanel8.add(btn_RpUtilidad, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setBackground(null);
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));
        jPanel9.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel9.setLayout(new java.awt.BorderLayout());

        btn_RpMoviminetos.setBackground(new java.awt.Color(102, 255, 102));
        btn_RpMoviminetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RpMoviminetosActionPerformed(evt);
            }
        });
        jPanel9.add(btn_RpMoviminetos, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 550, 320));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1284, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RpVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpVentasActionPerformed
        // TODO add your handling code here:
        this.RPventas.setVisible(true);
       
    }//GEN-LAST:event_btn_RpVentasActionPerformed

    private void btn_RpComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpComprasActionPerformed
        // TODO add your handling code here:
        this.RPcompras.setVisible(true);
       
    }//GEN-LAST:event_btn_RpComprasActionPerformed

    private void btn_RpTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpTrabajadorActionPerformed
        // TODO add your handling code here:
        this.RPtrabajador.setVisible(true);
       
    }//GEN-LAST:event_btn_RpTrabajadorActionPerformed

    private void btn_RpClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpClientesActionPerformed
        // TODO add your handling code here:
        this.RPclientes.setVisible(true);
   
    }//GEN-LAST:event_btn_RpClientesActionPerformed

    private void btn_RpCProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpCProveedorActionPerformed
        // TODO add your handling code here:
        this.RPproveedor.setVisible(true);
    }//GEN-LAST:event_btn_RpCProveedorActionPerformed

    private void btn_RpProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpProductosActionPerformed
        // TODO add your handling code here:
        this.RPproductos.setVisible(true);
    }//GEN-LAST:event_btn_RpProductosActionPerformed

    private void btn_RpUtilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpUtilidadActionPerformed
        // TODO add your handling code here:
        this.RPutilidad.setVisible(true);
    }//GEN-LAST:event_btn_RpUtilidadActionPerformed

    private void btn_RpMoviminetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RpMoviminetosActionPerformed
        // TODO add your handling code here:
        this.RPmovimientos.setVisible(true);
    }//GEN-LAST:event_btn_RpMoviminetosActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RpCProveedor;
    private javax.swing.JButton btn_RpClientes;
    private javax.swing.JButton btn_RpCompras;
    private javax.swing.JButton btn_RpMoviminetos;
    private javax.swing.JButton btn_RpProductos;
    private javax.swing.JButton btn_RpTrabajador;
    private javax.swing.JButton btn_RpUtilidad;
    private javax.swing.JButton btn_RpVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
